### ISSUE TITLE
App size is too high

### ISSUE THREAD

**Issue by araafroyall** [Xposed-Modules-Repo/com.pyshivam.geergit#1]
Xposed modules should be max of 5MB but your app is of about 45+MB . i dont understand why the size is too high

**Comment by pyshivam** [comment]
Thank you for reaching out and expressing your concern about the size of our app. We understand that app size can be an important consideration for some users.

The reason for the larger size of our app, around 45+MB, is primarily due to the technology we have used to develop it. Our app is built using Flutter, a cross-platform framework for mobile app development. Flutter apps are compiled into what is known as a "fat APK" or "fat bundle," which includes code for multiple target architectures (typically ARM, ARM64, and x86). This ensures compatibility with a wide range of devices, but it does result in a larger overall file size.

Additionally, our app may include various features, resources, and dependencies that contribute to its size. This could include graphics, multimedia files, libraries, or other components necessary for providing a rich and functional user experience.

While we strive to optimize our app's size wherever possible, the nature of the framework and the requirements of supporting multiple architectures can lead to larger file sizes compared to apps developed using alternative methods.

We appreciate your feedback, and we'll continue to explore ways to optimize the app's size without compromising its functionality. If you have any further questions or concerns, please feel free to let us know.

**Comment by araafroyall** [comment]
why you not use a zip module or similar method to install only necessary file for different architectures devices , like split apks , so only required apk will install with original base apk. hope you understand what i trying to say
